// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ImportProfileContent(arg1, arg2) {
  return window['go']['main']['App']['ImportProfileContent'](arg1, arg2);
}

export function OpenProfilesDir() {
  return window['go']['main']['App']['OpenProfilesDir']();
}

export function Profiles() {
  return window['go']['main']['App']['Profiles']();
}

export function ProfilesDir() {
  return window['go']['main']['App']['ProfilesDir']();
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
