// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';
import {main} from '../models';

export function AddExclusion(arg1:string):Promise<void>;

export function CheckWintun():Promise<boolean>;

export function Connect(arg1:client.Config):Promise<void>;

export function ConnectProfile(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DisableAdapter(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DownloadWintun():Promise<void>;

export function EnrollDevice(arg1:string):Promise<client.EnrollResult>;

export function FindConflictAdapters():Promise<Array<main.ConflictAdapter>>;

export function GetConnections():Promise<Array<client.ConnEntry>>;

export function GetEnrollments():Promise<Array<client.EnrollState>>;

export function GetGlobalSettings():Promise<client.GlobalSettings>;

export function GetPendingDeepLink():Promise<string>;

export function HandleURLOpen(arg1:string):Promise<void>;

export function ImportProfile():Promise<client.Profile>;

export function ImportProfileContent(arg1:string,arg2:string):Promise<client.Profile>;

export function ImportProfileFromText(arg1:string,arg2:string):Promise<client.Profile>;

export function OpenProfilesDir():Promise<void>;

export function PingAll():Promise<Record<string, number>>;

export function Profiles():Promise<Array<client.Profile>>;

export function ProfilesDir():Promise<string>;

export function ReadClipboard():Promise<string>;

export function ReadLogs(arg1:number):Promise<string>;

export function ReadProfileContent(arg1:string):Promise<string>;

export function SaveGlobalSettings(arg1:client.GlobalSettings):Promise<void>;

export function SaveProfileContent(arg1:string,arg2:string):Promise<void>;

export function Status():Promise<Record<string, any>>;
