// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExclusion(arg1) {
  return window['go']['main']['App']['AddExclusion'](arg1);
}

export function CheckWintun() {
  return window['go']['main']['App']['CheckWintun']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function ConnectProfile(arg1) {
  return window['go']['main']['App']['ConnectProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DisableAdapter(arg1) {
  return window['go']['main']['App']['DisableAdapter'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function DownloadWintun() {
  return window['go']['main']['App']['DownloadWintun']();
}

export function EnrollDevice(arg1) {
  return window['go']['main']['App']['EnrollDevice'](arg1);
}

export function FindConflictAdapters() {
  return window['go']['main']['App']['FindConflictAdapters']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetEnrollments() {
  return window['go']['main']['App']['GetEnrollments']();
}

export function GetGlobalSettings() {
  return window['go']['main']['App']['GetGlobalSettings']();
}

export function GetPendingDeepLink() {
  return window['go']['main']['App']['GetPendingDeepLink']();
}

export function HandleURLOpen(arg1) {
  return window['go']['main']['App']['HandleURLOpen'](arg1);
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ImportProfileContent(arg1, arg2) {
  return window['go']['main']['App']['ImportProfileContent'](arg1, arg2);
}

export function ImportProfileFromText(arg1, arg2) {
  return window['go']['main']['App']['ImportProfileFromText'](arg1, arg2);
}

export function OpenProfilesDir() {
  return window['go']['main']['App']['OpenProfilesDir']();
}

export function PingAll() {
  return window['go']['main']['App']['PingAll']();
}

export function Profiles() {
  return window['go']['main']['App']['Profiles']();
}

export function ProfilesDir() {
  return window['go']['main']['App']['ProfilesDir']();
}

export function ReadClipboard() {
  return window['go']['main']['App']['ReadClipboard']();
}

export function ReadLogs(arg1) {
  return window['go']['main']['App']['ReadLogs'](arg1);
}

export function ReadProfileContent(arg1) {
  return window['go']['main']['App']['ReadProfileContent'](arg1);
}

export function SaveGlobalSettings(arg1) {
  return window['go']['main']['App']['SaveGlobalSettings'](arg1);
}

export function SaveProfileContent(arg1, arg2) {
  return window['go']['main']['App']['SaveProfileContent'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}
