// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {client} from '../models';

export function Connect(arg1:client.Config):Promise<void>;

export function ConnectProfile(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function ImportProfile():Promise<client.Profile>;

export function ImportProfileContent(arg1:string,arg2:string):Promise<client.Profile>;

export function OpenProfilesDir():Promise<void>;

export function Profiles():Promise<Array<client.Profile>>;

export function ProfilesDir():Promise<string>;

export function Status():Promise<Record<string, any>>;
